Homework3
made-ml-in-prod-2021/cosinus01 pull request #2
Opened 2021-06-09 19:10 UTC by cosinus01

Сделан простенький проект
Реализованы генерация данных, обучение/валидация и предсказание на "потоке"

Тестов не успел, DockerOperator почему-то не заработал ни в каком виде :( (ни примеры 10_docker, 11_docker, ни свои собственные)

Доп баллы не собрал.
Оценка 21 балл (5 + 10 + 5 + 1)
 

Ниже скрины работающего airflow

![image](https://user-images.githubusercontent.com/41586304/121414512-6223d380-c96f-11eb-8320-4de728e50711.png)

![image](https://user-images.githubusercontent.com/41586304/121414557-7071ef80-c96f-11eb-8805-7e5fa295fef0.png)

![image](https://user-images.githubusercontent.com/41586304/121414591-78ca2a80-c96f-11eb-90fa-276571a9fd00.png)

![image](https://user-images.githubusercontent.com/41586304/121414612-7ec00b80-c96f-11eb-9676-6d2e358ec8c1.png)

2021-06-12 18:14 UTC, KernelA commented
У меня после запуска постоянно перезапускается webserver и scheduler:

Пример логов из docker-compose:
```
postgres_1   | 2021-06-12 18:12:31.990 UTC [80] ERROR:  relation "job" does not exist at character 13
postgres_1   | 2021-06-12 18:12:31.990 UTC [80] STATEMENT:  INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (NULL, 'running', 'SchedulerJob', '2021-06-12T18:12:31.988323+00:00'::timestamptz, NULL, '2021-06-12T18:12:31.988335+00:00'::timestamptz, 'LocalExecutor', '0f828419c71d', 'root') RETURNING job.id
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
scheduler_1  |     cursor, statement, parameters, context
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
scheduler_1  |     cursor.execute(statement, parameters)
scheduler_1  | psycopg2.errors.UndefinedTable: relation "job" does not exist
scheduler_1  | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...
scheduler_1  |                     ^
scheduler_1  |
scheduler_1  |
scheduler_1  | The above exception was the direct cause of the following exception:
scheduler_1  |
scheduler_1  | Traceback (most recent call last):
scheduler_1  |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
scheduler_1  |     sys.exit(main())
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
scheduler_1  |     args.func(args)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
scheduler_1  |     return func(*args, **kwargs)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
scheduler_1  |     return f(*args, **kwargs)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/scheduler_command.py", line 63, in scheduler
scheduler_1  |     job.run()
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 233, in run
scheduler_1  |     session.commit()
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
scheduler_1  |     self.transaction.commit()
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
scheduler_1  |     self._prepare_impl()
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
scheduler_1  |     self.session.flush()
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
scheduler_1  |     self._flush(objects)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
scheduler_1  |     transaction.rollback(_capture_exception=True)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
scheduler_1  |     with_traceback=exc_tb,
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
scheduler_1  |     flush_context.execute()
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
scheduler_1  |     rec.execute(self)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
scheduler_1  |     uow,
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
scheduler_1  |     insert,
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
scheduler_1  |     statement, params
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
scheduler_1  |     return meth(self, multiparams, params)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
scheduler_1  |     return connection._execute_clauseelement(self, multiparams, params)
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
scheduler_1  |     distilled_params,
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
scheduler_1  |     e, statement, parameters, cursor, context
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
scheduler_1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
scheduler_1  |     raise exception
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
scheduler_1  |     cursor, statement, parameters, context
scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
scheduler_1  |     cursor.execute(statement, parameters)
scheduler_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "job" does not exist
scheduler_1  | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...
scheduler_1  |                     ^
scheduler_1  |
scheduler_1  | [SQL: INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (%(dag_id)s, %(state)s, %(job_type)s, %(start_date)s, %(end_date)s, %(latest_heartbeat)s, %(executor_class)s, %(hostname)s, %(unixname)s) RETURNING job.id]
scheduler_1  | [parameters: {'dag_id': None, 'state': 'running', 'job_type': 'SchedulerJob', 'start_date': datetime.datetime(2021, 6, 12, 18, 12, 31, 988323, tzinfo=Timezone('UTC')), 'end_date': None, 'latest_heartbeat': datetime.datetime(2021, 6, 12, 18, 12, 31, 988335, tzinfo=Timezone('UTC')), 'executor_class': 'LocalExecutor', 'hostname': '0f828419c71d', 'unixname': 'root'}]
scheduler_1  | (Background on this error at: http://sqlalche.me/e/13/f405)
airflow_ml_dags_scheduler_1 exited with code 1
```

webserver:
```
webserver_1  |   ____________       _____________
webserver_1  |  ____    |__( )_________  __/__  /________      __
webserver_1  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
webserver_1  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
webserver_1  |  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
webserver_1  | [2021-06-12 18:14:21,933] {dagbag.py:440} INFO - Filling up the DagBag from /dev/null
webserver_1  | [2021-06-12 18:14:21,981] {manager.py:727} WARNING - No user yet created, use flask fab command to do it.
postgres_1   | 2021-06-12 18:14:24.906 UTC [100] ERROR:  relation "dag" does not exist at character 749
postgres_1   | 2021-06-12 18:14:24.906 UTC [100] STATEMENT:  SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_descr [...]

2021-06-12 18:20 UTC, KernelA requested changes
Бинарный файл лучше в Git LFS добавить

2021-06-12 18:20 UTC, KernelA commented on README.md
> +Продолжается задача по прогнозу падения объектов на Землю
Тут не хватает описание как запускать надо.

2021-06-12 18:20 UTC, KernelA commented on airflow_ml_dags/dags/1_downloading.py
> +    # data_target.to_csv(os.path.join(output_dir, "target.csv"), index=None) # В моей структуре лучше хранить всё в одном файле
Тут я бы комментарии убрал совсем, если это финальная версия кода.

2021-06-12 18:20 UTC, KernelA commented on airflow_ml_dags/dags/1_downloading.py
> +    schedule_interval=None,
Тут же надо был настроить периодический запуск.

2021-06-12 18:20 UTC, KernelA commented on airflow_ml_dags/docker-compose.yml
> +  # ml_base:
Если это не нужно то лучше убрать комментарии.

2021-06-14 11:08 UTC, KernelA requested changes

2021-06-14 11:40 UTC, cosinus01 commented on README.md
> +Продолжается задача по прогнозу падения объектов на Землю
Согласен, правда это READme из первой ДЗ, там в описании есть как запускать. Я просто криво сделал и READme попал сюда

2021-06-14 11:40 UTC, cosinus01 commented on airflow_ml_dags/dags/1_downloading.py
> +    # data_target.to_csv(os.path.join(output_dir, "target.csv"), index=None) # В моей структуре лучше хранить всё в одном файле
это, скажем так, пояснение почему нет файла target.csv

2021-06-14 11:40 UTC, cosinus01 commented on airflow_ml_dags/dags/1_downloading.py
> +    schedule_interval=None,
согласен, исправлю

2021-06-14 11:40 UTC, cosinus01 commented on airflow_ml_dags/docker-compose.yml
> +  # ml_base:
согласен

2021-06-14 11:41 UTC, cosinus01 commented on airflow_ml_dags/docker-compose.yml
> +  init:
учту это в будущем

2021-06-17 07:47 UTC, cosinus01 commented
> У меня после запуска постоянно перезапускается webserver и scheduler:
> 
> Пример логов из docker-compose:
> 
> ```
> postgres_1   | 2021-06-12 18:12:31.990 UTC [80] ERROR:  relation "job" does not exist at character 13
> postgres_1   | 2021-06-12 18:12:31.990 UTC [80] STATEMENT:  INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (NULL, 'running', 'SchedulerJob', '2021-06-12T18:12:31.988323+00:00'::timestamptz, NULL, '2021-06-12T18:12:31.988335+00:00'::timestamptz, 'LocalExecutor', '0f828419c71d', 'root') RETURNING job.id
> scheduler_1  | Traceback (most recent call last):
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
> scheduler_1  |     cursor, statement, parameters, context
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
> scheduler_1  |     cursor.execute(statement, parameters)
> scheduler_1  | psycopg2.errors.UndefinedTable: relation "job" does not exist
> scheduler_1  | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...
> scheduler_1  |                     ^
> scheduler_1  |
> scheduler_1  |
> scheduler_1  | The above exception was the direct cause of the following exception:
> scheduler_1  |
> scheduler_1  | Traceback (most recent call last):
> scheduler_1  |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
> scheduler_1  |     sys.exit(main())
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
> scheduler_1  |     args.func(args)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
> scheduler_1  |     return func(*args, **kwargs)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
> scheduler_1  |     return f(*args, **kwargs)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/scheduler_command.py", line 63, in scheduler
> scheduler_1  |     job.run()
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 233, in run
> scheduler_1  |     session.commit()
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
> scheduler_1  |     self.transaction.commit()
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
> scheduler_1  |     self._prepare_impl()
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
> scheduler_1  |     self.session.flush()
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
> scheduler_1  |     self._flush(objects)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
> scheduler_1  |     transaction.rollback(_capture_exception=True)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
> scheduler_1  |     with_traceback=exc_tb,
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> scheduler_1  |     raise exception
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
> scheduler_1  |     flush_context.execute()
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
> scheduler_1  |     rec.execute(self)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
> scheduler_1  |     uow,
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
> scheduler_1  |     insert,
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
> scheduler_1  |     statement, params
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
> scheduler_1  |     return meth(self, multiparams, params)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
> scheduler_1  |     return connection._execute_clauseelement(self, multiparams, params)
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
> scheduler_1  |     distilled_params,
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
> scheduler_1  |     e, statement, parameters, cursor, context
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
> scheduler_1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> scheduler_1  |     raise exception
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
> scheduler_1  |     cursor, statement, parameters, context
> scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
> scheduler_1  |     cursor.execute(statement, parameters)
> scheduler_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "job" does not exist
> scheduler_1  | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...
> scheduler_1  |                     ^
> scheduler_1  |
> scheduler_1  | [SQL: INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (%(dag_id)s, %(state)s, %(job_type)s, %(start_date)s, %(end_date)s, %(latest_heartbeat)s, %(executor_class)s, %(hostname)s, %(unixname)s) RETURNING job.id]
> scheduler_1  | [parameters: {'dag_id': None, 'state': 'running', 'job_type': 'SchedulerJob', 'start_date': datetime.datetime(2021, 6, 12, 18, 12, 31, 988323, tzinfo=Timezone('UTC')), 'end_date': None, 'latest_heartbeat': datetime.datetime(2021, 6, 12, 18, 12, 31, 988335, tzinfo=Timezone('UTC')), 'executor_class': 'LocalExecutor', 'hostname': '0f828419c71d', 'unixname': 'root'}]
> scheduler_1  | (Background on this error at: http://sqlalche.me/e/13/f405)
> airflow_ml_dags_scheduler_1 exited with code 1
> ```
> 
> webserver:
> 
> ```
> webserver_1  |   ____________       _____________
> webserver_1  |  ____    |__( )_________  __/__  /________      __
> webserver_1  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
> webserver_1  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
> webserver_1  |  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
> webserver_1  | [2021-06-12 18:14:21,933] {dagbag.py:440} INFO - Filling up the DagBag from /dev/null
> webserver_1  | [2021-06-12 18:14:21,981] {manager.py:727} WARNING - No user yet created, use flask fab command to do it.
> postgres_1   | 2021-06-12 18:14:24.906 UTC [100] ERROR:  relation "dag" does not exist at character 749
> postgres_1   | 2021-06-12 18:14:24.906 UTC [100] STATEMENT:  SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag. [...]

2021-06-17 15:48 UTC, KernelA commented
> > У меня после запуска постоянно перезапускается webserver и scheduler:
> > Пример логов из docker-compose:
> > ```
> > postgres_1   | 2021-06-12 18:12:31.990 UTC [80] ERROR:  relation "job" does not exist at character 13
> > postgres_1   | 2021-06-12 18:12:31.990 UTC [80] STATEMENT:  INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (NULL, 'running', 'SchedulerJob', '2021-06-12T18:12:31.988323+00:00'::timestamptz, NULL, '2021-06-12T18:12:31.988335+00:00'::timestamptz, 'LocalExecutor', '0f828419c71d', 'root') RETURNING job.id
> > scheduler_1  | Traceback (most recent call last):
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
> > scheduler_1  |     cursor, statement, parameters, context
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
> > scheduler_1  |     cursor.execute(statement, parameters)
> > scheduler_1  | psycopg2.errors.UndefinedTable: relation "job" does not exist
> > scheduler_1  | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...
> > scheduler_1  |                     ^
> > scheduler_1  |
> > scheduler_1  |
> > scheduler_1  | The above exception was the direct cause of the following exception:
> > scheduler_1  |
> > scheduler_1  | Traceback (most recent call last):
> > scheduler_1  |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
> > scheduler_1  |     sys.exit(main())
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/__main__.py", line 40, in main
> > scheduler_1  |     args.func(args)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
> > scheduler_1  |     return func(*args, **kwargs)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 89, in wrapper
> > scheduler_1  |     return f(*args, **kwargs)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/scheduler_command.py", line 63, in scheduler
> > scheduler_1  |     job.run()
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 233, in run
> > scheduler_1  |     session.commit()
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1042, in commit
> > scheduler_1  |     self.transaction.commit()
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 504, in commit
> > scheduler_1  |     self._prepare_impl()
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
> > scheduler_1  |     self.session.flush()
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
> > scheduler_1  |     self._flush(objects)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
> > scheduler_1  |     transaction.rollback(_capture_exception=True)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
> > scheduler_1  |     with_traceback=exc_tb,
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> > scheduler_1  |     raise exception
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
> > scheduler_1  |     flush_context.execute()
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
> > scheduler_1  |     rec.execute(self)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
> > scheduler_1  |     uow,
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
> > scheduler_1  |     insert,
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
> > scheduler_1  |     statement, params
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
> > scheduler_1  |     return meth(self, multiparams, params)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
> > scheduler_1  |     return connection._execute_clauseelement(self, multiparams, params)
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
> > scheduler_1  |     distilled_params,
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
> > scheduler_1  |     e, statement, parameters, cursor, context
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
> > scheduler_1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> > scheduler_1  |     raise exception
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
> > scheduler_1  |     cursor, statement, parameters, context
> > scheduler_1  |   File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
> > scheduler_1  |     cursor.execute(statement, parameters)
> > scheduler_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "job" does not exist
> > scheduler_1  | LINE 1: INSERT INTO job (dag_id, state, job_type, start_date, end_da...
> > scheduler_1  |                     ^
> > scheduler_1  |
> > scheduler_1  | [SQL: INSERT INTO job (dag_id, state, job_type, start_date, end_date, latest_heartbeat, executor_class, hostname, unixname) VALUES (%(dag_id)s, %(state)s, %(job_type)s, %(start_date)s, %(end_date)s, %(latest_heartbeat)s, %(executor_class)s, %(hostname)s, %(unixname)s) RETURNING job.id]
> > scheduler_1  | [parameters: {'dag_id': None, 'state': 'running', 'job_type': 'SchedulerJob', 'start_date': datetime.datetime(2021, 6, 12, 18, 12, 31, 988323, tzinfo=Timezone('UTC')), 'end_date': None, 'latest_heartbeat': datetime.datetime(2021, 6, 12, 18, 12, 31, 988335, tzinfo=Timezone('UTC')), 'executor_class': 'LocalExecutor', 'hostname': '0f828419c71d', 'unixname': 'root'}]
> > scheduler_1  | (Background on this error at: http://sqlalche.me/e/13/f405)
> > airflow_ml_dags_scheduler_1 exited with code 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > webserver:
> > ```
> > webserver_1  |   ____________       _____________
> > webserver_1  |  ____    |__( )_________  __/__  /________      __
> > webserver_1  | ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
> > webserver_1  | ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
> > webserver_1  |  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
> > webserver_1  | [2021-06-12 18:14:21,933] {dagbag.py:440} INFO - Filling up the DagBag from /dev/null
> > webserver_1  | [2021-06-12 18:14:21,981] {manager.py:727} WARNING - No user yet created, use flask fab command to do it.
> > postgres_1   | 2021-06-12 18:14:24.906 UTC [100] ERROR:  relation "dag" does not exist at character 749
> > postgres_1   | 2021-06-12 18:14:24.906 UTC [100] STATEMENT:  SELE [...]

2021-06-18 13:48 UTC, Mikhail-M approved these changes
Баллы: 20

2021-06-18 13:52 UTC, merged